version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Build documentation
          command: |
             cd docs
             pip install -r requirements.txt
             make html
          timeout: "3600"
      - store_artifacts:
          path: docs/_build/html
