on: 
  push:
    branches:
      - main  
  pull_request: []

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ReadTheDocs to GitHub Pages
    steps:
      - uses: actions/checkout@v2

        # Buid on push (but no deploy)
      - uses: rse-ops/librarian/readthedocs@main
        if: (github.event_name == 'push')
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 

      - uses: rse-ops/librarian/readthedocs@main
        if: (github.event_name == 'pull_request')
        with:        
          deploy: "false"

